(()=>{
'use strict';
function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn,{once:true});else fn()}
ready(()=>{
 const bar=document.createElement('aside');bar.className='site-utility';bar.setAttribute('aria-label','Website tools');
 bar.innerHTML='<div class="container utility-inner"><time class="utility-clock" id="clinicClock"></time><div class="utility-controls"><span>IST · भारत</span><button type="button" id="readingSize" aria-pressed="false">A+ मोठी अक्षरे</button><a href="tel:+919518355385">95183 55385</a></div></div>';
 document.body.prepend(bar);
 const clock=document.getElementById('clinicClock');function tick(){const now=new Date();const locale=document.documentElement.lang==='mr'?'mr-IN':'en-IN';clock.dateTime=now.toISOString();clock.textContent=new Intl.DateTimeFormat(locale,{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:true}).format(now)}tick();setInterval(tick,1000);
 const size=document.getElementById('readingSize');function setSize(large){document.documentElement.classList.toggle('large-reading',large);size.setAttribute('aria-pressed',String(large));size.textContent=large?'A− नेहमीची अक्षरे':'A+ मोठी अक्षरे';try{localStorage.setItem('clinic-large-reading',String(large))}catch(e){}}try{setSize(localStorage.getItem('clinic-large-reading')==='true')}catch(e){}size.onclick=()=>setSize(!document.documentElement.classList.contains('large-reading'));
 const top=document.createElement('button');top.type='button';top.className='back-top';top.textContent='↑';top.setAttribute('aria-label','Back to top / वर जा');top.hidden=true;document.body.append(top);addEventListener('scroll',()=>{top.hidden=scrollY<500},{passive:true});top.onclick=()=>window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 const footer=document.querySelector('.footer .container');if(footer){const stats=document.createElement('div');stats.className='site-statistics';stats.innerHTML='<div><strong>वेबसाइटवरील पान-दृश्ये / Page views</strong><small>२६ सप्टेंबर २०२६ पासूनची नोंद · ही वेगवेगळ्या व्यक्तींची संख्या नाही.</small><small>Public counter powered by Hits.sh; repeat views and service availability affect the count.</small></div><div><img id="pageViewBadge" alt="Page views counter" referrerpolicy="no-referrer"><span class="visit-fallback" hidden>काउंटर सध्या उपलब्ध नाही / Counter unavailable</span></div>';footer.append(stats);const badge=stats.querySelector('img');badge.onerror=()=>{badge.hidden=true;stats.querySelector('.visit-fallback').hidden=false};badge.src='https://hits.sh/drvishnukantdamchu-dotcom.github.io/Vishnu-Ayurved-Clinic-Udgir.svg?label=Page%20views&color=c29b49&labelColor=123f35';}
});
})();
