import {getAuthProvider} from './auth-context.mjs?v=35';
'use strict';
function visitTypeLabel(value){return ({'नवीन':'New','फॉलो-अप':'Follow-up'})[value]||value}
function genderLabel(value){return ({'स्त्री':'Female','पुरुष':'Male','इतर':'Other','नोंद नाही':'Not recorded'})[value]||value}
const samples=[];
const titles={dashboard:'Today’s overview',patients:'Patient search',review:'Doctor review',followups:'Follow-ups',panchakarma:'Panchakarma',reports:'Monthly reports',settings:'Settings'};
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{Object.keys(titles).forEach(id=>document.getElementById(id).hidden=id!==b.dataset.page);document.getElementById('title').textContent=titles[b.dataset.page];document.querySelectorAll('nav button').forEach(n=>{n.removeAttribute('aria-current');if(n.dataset.page===b.dataset.page)n.setAttribute('aria-current','page')})}));
function render(target,list){target.replaceChildren();if(!list.length){target.textContent='No matching record found.';return}list.forEach(p=>{const row=document.createElement('div');row.className='row';row.dataset.patientId=p.id;const icon=document.createElement('span');icon.className='avatar';icon.textContent=p.name.slice(0,1).toUpperCase();const details=document.createElement('div');const name=document.createElement('b');name.textContent=p.name;const sub=document.createElement('small');sub.textContent=`${p.id} · ${p.village} · ${visitTypeLabel(p.type)}`;details.append(name,sub);const btn=document.createElement('button');btn.textContent='Case paper';btn.addEventListener('click',()=>showCase(p));row.append(icon,details,btn);target.append(row)})}
function showCase(p){const box=document.getElementById('case-content');box.replaceChildren();const head=document.getElementById('case-letterhead');head.replaceChildren();const img=document.createElement('img');img.src='../images/header-restored-20260926.webp';img.alt='Clinic letterhead';img.className='clinic-header';head.append(img);const title=document.createElement('h2');title.textContent='Vishnu Ayurved Clinic & Panchakarma Center';const doctor=document.createElement('p');doctor.textContent='Dr. Vishnukant R. Jadhav · BAMS, MD (Ayurved), Ph.D. Scholar';const address=document.createElement('p');address.textContent='Dolphin Statue, Chhatrapati Shahu Maharaj Chowk, Shelhal Road, Udgir · 95183 55385';const identity=document.createElement('div');identity.className='patient-identity';for(const [label,value]of [['Patient',p.name],['Patient ID',p.id],['Visit date',p.visitDate],['Age / gender',(p.age||'—')+' / '+genderLabel(p.gender)],['Village',p.village],['Mobile',p.mobile]]){const line=document.createElement('p');const strong=document.createElement('b');strong.textContent=label+': ';line.append(strong,document.createTextNode(value||'Not recorded'));identity.append(line)}head.append(title,doctor,address,identity);document.getElementById('case-title').textContent=p.name+' · '+(p.visitDate||'');const manage=document.getElementById('case-manage');manage.hidden=getAuthProvider()?.current()?.role!=='owner';manage.onclick=()=>{document.getElementById('case').close();document.querySelector('nav [data-page="settings"]').click();document.dispatchEvent(new CustomEvent('opd-manage-patient',{detail:p}));};document.getElementById('case').showModal()}
const originalRender=render;
render=function(target,list){originalRender(target,list);target.querySelectorAll('.row').forEach((row,i)=>{const button=document.createElement('button');button.textContent='Prescription';button.className='prescription-open';button.onclick=()=>{showCase(list[i]);requestAnimationFrame(()=>{const editor=document.getElementById('prescription-editor');if(editor){editor.scrollIntoView({block:'start'});editor.querySelector('textarea')?.focus({preventScroll:true})}else{const note=document.createElement('p');note.textContent='Prescription section did not load. Refresh the page and try again.';note.setAttribute('role','alert');document.getElementById('case-content').append(note)}})};row.append(button)})};
render(document.getElementById('queue'),samples);render(document.getElementById('results'),samples);
document.addEventListener('opd-request-samples',()=>document.dispatchEvent(new CustomEvent('opd-samples-ready',{detail:samples})));
document.addEventListener('opd-filtered',e=>render(document.getElementById('results'),e.detail));
document.addEventListener('opd-open-patient',e=>showCase(e.detail));
document.addEventListener('opd-added',e=>{const i=samples.findIndex(p=>p.id===e.detail.id);if(i<0)samples.push(e.detail);else samples[i]=e.detail;render(document.getElementById('queue'),samples);document.querySelector('.stats article strong').textContent=String(samples.length);document.querySelectorAll('.stats article strong')[1].textContent=String(samples.filter(p=>p.type==='नवीन').length);document.querySelectorAll('.stats article strong')[2].textContent=String(samples.filter(p=>p.type==='फॉलो-अप').length)});
document.addEventListener('DOMContentLoaded',()=>document.dispatchEvent(new CustomEvent('opd-samples-ready',{detail:samples})));
document.getElementById('close').onclick=()=>document.getElementById('case').close();
function printCase(mode){document.body.dataset.casePrint=mode;window.print()}
document.getElementById('print').onclick=()=>printCase('case');document.getElementById('print-rx').onclick=()=>printCase('prescription');document.getElementById('print-both').onclick=()=>printCase('both');window.addEventListener('afterprint',()=>delete document.body.dataset.casePrint);
document.getElementById('ribbon-pause').onclick=e=>{const paused=document.querySelector('.status-ribbon').classList.toggle('paused');e.target.textContent=paused?'Resume motion':'Pause motion';e.target.setAttribute('aria-pressed',String(paused))};
const originalShowCase=showCase;
showCase=function(p){originalShowCase(p);document.dispatchEvent(new CustomEvent('opd-case-open',{detail:p}))};
document.getElementById('date').textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'full',timeZone:'Asia/Kolkata'}).format(new Date());
document.getElementById('text-size').onclick=e=>{const active=document.body.classList.toggle('large');e.target.setAttribute('aria-pressed',String(active))};
function network(){document.getElementById('network').textContent=navigator.onLine?'Online · Cloud sync available in Settings':'Offline · Changes saved on this device'}
window.addEventListener('online',network);window.addEventListener('offline',network);
network();
let promptEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;document.getElementById('install').hidden=false});document.getElementById('install').onclick=async()=>{if(promptEvent){await promptEvent.prompt();promptEvent=null;document.getElementById('install').hidden=true}};
if('serviceWorker' in navigator && /^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{document.getElementById('network').textContent+=' · Offline shell unavailable'});
