'use strict';
const samples=[{id:'VAC-DEMO-001',name:'नमुना रुग्ण अ',village:'उदगीर',type:'नवीन'},{id:'VAC-DEMO-002',name:'नमुना रुग्ण ब',village:'शेल्हाळ',type:'फॉलो-अप'},{id:'VAC-DEMO-003',name:'नमुना रुग्ण क',village:'उदगीर',type:'नवीन'}];
const titles={dashboard:'आजचा आढावा',patients:'रुग्ण शोध',panchakarma:'पंचकर्म',reports:'मासिक अहवाल',settings:'सेटिंग्ज'};
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>{Object.keys(titles).forEach(id=>document.getElementById(id).hidden=id!==b.dataset.page);document.getElementById('title').textContent=titles[b.dataset.page];document.querySelectorAll('nav button').forEach(n=>{n.removeAttribute('aria-current');if(n.dataset.page===b.dataset.page)n.setAttribute('aria-current','page')})}));
function render(target,list){target.replaceChildren();if(!list.length){target.textContent='जुळणारी नमुना नोंद सापडली नाही.';return}list.forEach(p=>{const row=document.createElement('div');row.className='row';const icon=document.createElement('span');icon.className='avatar';icon.textContent='न';const details=document.createElement('div');const name=document.createElement('b');name.textContent=p.name;const sub=document.createElement('small');sub.textContent=`${p.id} · ${p.village} · ${p.type}`;details.append(name,sub);const btn=document.createElement('button');btn.textContent='केस पेपर';btn.addEventListener('click',()=>showCase(p));row.append(icon,details,btn);target.append(row)})}
function showCase(p){const box=document.getElementById('case-content');box.replaceChildren();const img=document.createElement('img');img.src='../images/header-restored-20260926.webp';img.alt='Clinic header';img.className='clinic-header';box.append(img);for(const text of ['नमुना केस पेपर — वैद्यकीय वापरासाठी नाही',p.name,`${p.id} · ${p.village} · ${p.type}`,'ही काल्पनिक नोंद आहे. खरा इतिहास, निदान किंवा उपचार उपलब्ध नाहीत.','Dr. Jadhav V. R. · BAMS, MD (Ayurved), Ph.D. Scholar','Dolphin Statue, Chhatrapati Shahu Maharaj Chowk, Shelhal Road, Udgir · 95183 55385']){const el=document.createElement('p');el.textContent=text;box.append(el)}document.getElementById('case').showModal()}
render(document.getElementById('queue'),samples);render(document.getElementById('results'),samples);
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.trim().toLocaleLowerCase();render(document.getElementById('results'),samples.filter(p=>`${p.name} ${p.id} ${p.village}`.toLocaleLowerCase().includes(q)))});
document.getElementById('close').onclick=()=>document.getElementById('case').close();document.getElementById('print').onclick=()=>window.print();
document.getElementById('date').textContent=new Intl.DateTimeFormat('mr-IN',{dateStyle:'full',timeZone:'Asia/Kolkata'}).format(new Date());
document.getElementById('text-size').onclick=e=>{const active=document.body.classList.toggle('large');e.target.setAttribute('aria-pressed',String(active))};
const month=document.getElementById('month');month.value=new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date()).replace('/','-');function report(){document.getElementById('report-note').textContent=`निवड: ${month.value || 'महिना निवडा'} · प्रत्यक्ष डेटाबेस अद्याप जोडलेला नाही.`}month.onchange=report;report();
function network(){document.getElementById('network').textContent=navigator.onLine?'इंटरनेट उपलब्ध · Cloud sync बंद':'ऑफलाइन · Cloud sync बंद'}window.addEventListener('online',network);window.addEventListener('offline',network);network();
let promptEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;document.getElementById('install').hidden=false});document.getElementById('install').onclick=async()=>{if(promptEvent){await promptEvent.prompt();promptEvent=null;document.getElementById('install').hidden=true}};
if('serviceWorker' in navigator && /^https?:$/.test(location.protocol))navigator.serviceWorker.register('./sw.js').catch(()=>{document.getElementById('network').textContent+=' · Offline shell unavailable'});
