import {exportDemo,importDemo} from './demo-store.mjs?v=30';
const settings=document.getElementById('settings');
const box=document.createElement('section');box.className='panel';
const title=document.createElement('h3');title.textContent='Local clinic records: Backup / restore';
const warning=document.createElement('p');warning.textContent='Backup contains patient records and attached reports. Keep the backup private and store a copy in a secure location. There is no automatic cloud backup.';
const button=document.createElement('button');button.type='button';button.textContent='Download backup';
const label=document.createElement('label');label.textContent='Choose backup JSON';const input=document.createElement('input');input.type='file';input.accept='.json,application/json';label.append(input);
const restore=document.createElement('button');restore.type='button';restore.textContent='Restore backup';
const status=document.createElement('p');status.setAttribute('role','status');box.append(title,warning,button,label,restore,status);settings.append(box);
button.onclick=async()=>{try{const backup=await exportDemo();const url=URL.createObjectURL(new Blob([JSON.stringify(backup)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`vac-opd-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent=`${backup.records.length} local clinic records included in backup.`}catch{status.textContent='Backup failed. Check browser storage.'}};
restore.onclick=async()=>{const file=input.files?.[0];if(!file){status.textContent='Choose a JSON file first.';return}if(file.size>100*1024*1024){status.textContent='The file exceeds 100 MB.';return}if(!confirm('Restore the backup? Matching clinic records on this device may be replaced.'))return;try{const backup=JSON.parse(await file.text());const count=await importDemo(backup);status.textContent=`${count} clinic records restored. Refresh the page.`}catch{status.textContent='Invalid backup or restore failed. Check that you selected a clinic backup file.'}};
