import test from 'node:test';import assert from 'node:assert/strict';import {syncClinic} from './clinic-sync.mjs';
const row={kind:'clinical',id:'VAC-OPD-20261002-x',value:{complaints:[],values:{}},dirty:true,updatedAt:'now'};
function setup(remote=[]){const writes=[],acks=[];return {writes,acks,args:{auth:{current:()=>({uid:'owner',role:'owner'}),listClinicRecords:async()=>remote,saveClinicRecord:async r=>{writes.push(r);return {...r,payload:JSON.stringify(r.value),revision:'new'}}},localRows:async()=>[row],ack:async(r,time)=>{acks.push({r,time});return true}}}}
test('clinic edit uploads with acknowledgment bound to its local version',async()=>{const s=setup();const result=await syncClinic(s.args);assert.equal(result.uploaded,1);assert.equal(s.acks[0].time,'now');});
test('different cloud and local edits are kept as conflicts without overwrite',async()=>{const s=setup([{...row,payload:'{"different":true}',revision:'changed'}]);const result=await syncClinic(s.args);assert.equal(s.writes.length,0);assert.equal(result.conflicts.length,1);});
test('lost response retry acknowledges identical remote contents without another write',async()=>{const s=setup([{...row,payload:JSON.stringify(row.value),deleted:false,revision:'saved'}]);const result=await syncClinic(s.args);assert.equal(s.writes.length,0);assert.equal(result.conflicts.length,0);assert.equal(s.acks[0].time,'now');});
test('failed upload remains local and is reported',async()=>{const s=setup();s.args.auth.saveClinicRecord=async()=>{throw Object.assign(new Error(),{code:'PERMISSION_DENIED'})};const result=await syncClinic(s.args);assert.equal(result.failures[0].code,'PERMISSION_DENIED');assert.equal(s.acks.length,0);});
test('student runner never uploads prescriptions',async()=>{const s=setup();s.args.auth.current=()=>({uid:'student',role:'student'});s.args.localRows=async()=>[{...row,kind:'prescription'}];const result=await syncClinic(s.args);assert.equal(s.writes.length,0);assert.equal(result.uploaded,0);});
test('session change stops cloud import',async()=>{const s=setup();s.args.isCurrent=()=>false;await assert.rejects(syncClinic(s.args),/SESSION_CHANGED/);assert.equal(s.writes.length,0);assert.equal(s.acks.length,0);});
