import {allDemo} from './demo-store.mjs?v=35';
import {todayIST} from './patient-model.mjs?v=35';
import {dashboardMetrics} from './dashboard-model.mjs?v=35';
const panel=document.createElement('section');panel.className='panel insights';panel.innerHTML='<div class="section-head"><div><span class="eyebrow">CLINIC INSIGHTS</span><h2>Records at a glance</h2></div><label>Month<input id="insight-month" type="month"></label><button id="insight-refresh">Refresh insights</button></div><p class="muted">Based on loaded intake records. Diagnosis labels are clinician-entered; one patient can have multiple labels. These counts are not a complete visit ledger.</p><div id="insight-stats" class="stats"></div><div class="chart-grid"><section><h3>Intakes by date</h3><div id="chart-daily" class="bar-chart"></div></section><section><h3>Diagnosis / dosha labels</h3><div id="chart-diagnosis" class="bar-chart"></div></section><section><h3>Review status</h3><div id="chart-status" class="bar-chart"></div></section></div><p id="insight-time" class="muted" role="status"></p>';
document.getElementById('dashboard').prepend(panel);const month=panel.querySelector('#insight-month');month.value=todayIST().slice(0,7);let timer,generation=0;
function bars(id,rows,tone){const box=panel.querySelector(id);box.replaceChildren();if(!rows.length){box.textContent='No records in this period.';return}const max=Math.max(...rows.map(r=>r[1]),1);for(const [label,count]of rows){const row=document.createElement('div');row.className='chart-row';const text=document.createElement('span');text.textContent=label;const track=document.createElement('div');track.className='chart-track '+tone;const fill=document.createElement('span');fill.style.width=`${count/max*100}%`;track.append(fill);const number=document.createElement('strong');number.textContent=count;row.append(text,track,number);box.append(row)}}
async function draw(){const run=++generation;try{const [intakes,rx,review,followup]=await Promise.all(['intake','prescription','review','followup'].map(k=>allDemo(k)));if(run!==generation)return;const m=dashboardMetrics(intakes.map(r=>r.value),rx,review,followup,month.value,todayIST());const stats=panel.querySelector('#insight-stats');stats.replaceChildren();for(const [label,count]of [['Today’s intakes',m.today],['Selected month',m.period],['Review pending',m.status.pending],['Follow-ups due / overdue',m.followupsDue]]){const card=document.createElement('article');const text=document.createElement('span');text.textContent=label;const n=document.createElement('strong');n.textContent=count;card.append(text,n);stats.append(card)}bars('#chart-daily',m.daily,'teal');bars('#chart-diagnosis',m.diagnoses.slice(0,8),'violet');bars('#chart-status',[['Reviewed',m.status.reviewed],['Pending review',m.status.pending],['Prescription not recorded',m.status.noPrescription]],'amber');const top=document.querySelector('#dashboard>.stats');if(top){const values=top.querySelectorAll('strong');[m.total,m.newPatients,m.followupIntakes].forEach((n,i)=>values[i].textContent=n)}panel.querySelector('#insight-time').textContent='Updated '+new Intl.DateTimeFormat('en-IN',{timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date())+' · counts from records loaded on this device.';const ribbons=document.querySelectorAll('.ribbon-count');ribbons.forEach(e=>e.textContent=`${m.total} active records · ${m.today} intakes today · ${m.followupsDue} follow-ups due`);const reviewMap=new Map(review.map(r=>[r.id,r.value.status]));const rxIds=new Set(rx.map(r=>r.id));document.querySelectorAll('.row[data-patient-id]').forEach(row=>{let badge=row.querySelector('.record-badge');if(!badge){badge=document.createElement('span');row.append(badge)}const reviewed=reviewMap.get(row.dataset.patientId)==='reviewed';badge.className='record-badge '+(reviewed?'badge-reviewed':rxIds.has(row.dataset.patientId)?'badge-prescribed':'badge-pending');badge.textContent=reviewed?'Reviewed':rxIds.has(row.dataset.patientId)?'Prescription saved':'Entry / review pending'})}catch{panel.querySelector('#insight-time').textContent='Insights could not load. Saved records are retained.'}}
month.onchange=draw;panel.querySelector('#insight-refresh').onclick=draw;window.addEventListener('opd-local-save',()=>{clearTimeout(timer);timer=setTimeout(draw,300)});document.addEventListener('opd-added',()=>{clearTimeout(timer);timer=setTimeout(draw,100)});document.addEventListener('opd-filtered',()=>{clearTimeout(timer);timer=setTimeout(draw,100)});draw();
function clock(){document.getElementById('live-clock').textContent=new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'medium',timeZone:'Asia/Kolkata'}).format(new Date())+' IST'}clock();setInterval(clock,1000);
