// Browser-local persistence for synthetic VAC-DEMO data only. Never use for real patient records.
const NAME='vac-opd-synthetic-v1';
const KINDS=new Set(['clinical','prescription','panchakarma','attachment','followup']);
export function syntheticId(id){return /^VAC-DEMO-[A-Za-z0-9_-]{1,140}$/.test(String(id||''))}
function open(){return new Promise((resolve,reject)=>{if(!globalThis.indexedDB){reject(new Error('STORAGE_UNAVAILABLE'));return}const request=indexedDB.open(NAME,1);request.onupgradeneeded=()=>{request.result.createObjectStore('records',{keyPath:'key'})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function operation(mode,action){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('records',mode),store=tx.objectStore('records');let result;const request=action(store);request.onsuccess=()=>{result=request.result};request.onerror=()=>reject(request.error);tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}})}
function key(kind,id){if(!KINDS.has(kind)||!syntheticId(id))throw new Error('SYNTHETIC_ONLY');return `${kind}:${id}`}
export async function getDemo(kind,id){const entry=await operation('readonly',s=>s.get(key(kind,id)));return entry?.value??null}
export async function putDemo(kind,id,value){return operation('readwrite',s=>s.put({key:key(kind,id),kind,id,value,updatedAt:new Date().toISOString()}))}
export async function deleteDemo(kind,id){return operation('readwrite',s=>s.delete(key(kind,id)))}
export async function allDemo(kind){if(!KINDS.has(kind))throw new Error('KIND_DENIED');const rows=await operation('readonly',s=>s.getAll());return rows.filter(r=>r.kind===kind&&syntheticId(r.id))}
export async function exportDemo(){const rows=await operation('readonly',s=>s.getAll());return {format:'vac-opd-synthetic-backup',version:1,exportedAt:new Date().toISOString(),records:await Promise.all(rows.filter(r=>KINDS.has(r.kind)&&syntheticId(r.id)).map(async r=>({...r,value:r.kind==='attachment'?await Promise.all(r.value.map(async item=>({...item,blob:await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(item.blob)} )}))):r.value})))} }
export async function importDemo(backup){if(backup?.format!=='vac-opd-synthetic-backup'||backup.version!==1||!Array.isArray(backup.records)||backup.records.length>10000)throw new Error('INVALID_BACKUP');const safe=[];for(const row of backup.records){key(row.kind,row.id);if(row.key!==`${row.kind}:${row.id}`)throw new Error('INVALID_BACKUP');let value=row.value;if(row.kind==='attachment'){if(!Array.isArray(value)||value.length>20)throw new Error('INVALID_BACKUP');value=value.map(item=>{const match=/^data:(application\/pdf|image\/jpeg|image\/png);base64,([A-Za-z0-9+/=]+)$/.exec(item.blob||'');if(!match||match[2].length>7_000_000)throw new Error('INVALID_BACKUP');const bytes=Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0));return {...item,blob:new Blob([bytes],{type:match[1]})}})}safe.push({key:row.key,kind:row.kind,id:row.id,value,updatedAt:row.updatedAt||new Date().toISOString()})}const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction('records','readwrite');for(const row of safe)tx.objectStore('records').put(row);tx.oncomplete=()=>{db.close();resolve(safe.length)};tx.onerror=()=>{db.close();reject(tx.error)};tx.onabort=()=>{db.close();reject(tx.error)}})}
