import {allDemo,putDemo,syntheticId} from './demo-store.mjs?v=19';
import {todayIST} from './patient-model.mjs';
const records=[];const patients=new Map();
const section=document.getElementById('panchakarma');section.replaceChildren();
const title=document.createElement('h2');title.textContent='पंचकर्म · दिवसनिहाय नमुना नोंदी';section.append(title);
const notice=document.createElement('p');notice.className='notice';notice.textContent='फक्त काल्पनिक माहिती. नोंदी या डिव्हाइसवर राहतात; Cloud sync नाही. हा उपचार सल्ला किंवा मंजूर उपचार आराखडा नाही.';section.append(notice);
const form=document.createElement('form');const grid=document.createElement('div');grid.className='form-grid';form.append(grid);
function field(name,label,type='text'){const l=document.createElement('label');l.textContent=label;const input=document.createElement(type==='select'?'select':'input');input.name=name;if(type!=='select')input.type=type;input.maxLength=600;l.append(input);grid.append(l);return input}
const select=field('patient','नमुना रुग्ण *','select');select.required=true;
function patientsChanged(){const previous=select.value;select.replaceChildren();const first=new Option('रुग्ण निवडा','');select.append(first);for(const p of patients.values())select.append(new Option(`${p.name} · ${p.id}`,p.id));if(patients.has(previous))select.value=previous}
document.addEventListener('opd-samples-ready',e=>{e.detail.forEach(p=>patients.set(p.id,p));patientsChanged()});document.addEventListener('opd-added',e=>{patients.set(e.detail.id,e.detail);patientsChanged()});
const course=field('course','कोर्सचे नाव *');course.required=true;course.placeholder='उदा. नमुना कोर्स अ';
const day=field('day','कोर्सचा दिवस *','number');day.min=1;day.max=365;day.step=1;day.required=true;
const date=field('date','प्रक्रियेची तारीख *','date');date.required=true;date.value=todayIST();date.max=todayIST();
field('time','वेळ','time');
const stage=field('stage','टप्पा','select');['पूर्वकर्म','प्रधानकर्म','पश्चात्कर्म','स्थानिक उपचार','इतर'].forEach(v=>stage.append(new Option(v,v)));
const procedure=field('procedure','प्रक्रिया *');procedure.required=true;procedure.setAttribute('list','pk-procedures');const options=document.createElement('datalist');options.id='pk-procedures';['दीपन–पाचन','स्नेहपान','अभ्यंग','स्वेदन','वमन','विरेचन','निरूह बस्ती','अनुवासन बस्ती','मात्राबस्ती','नस्य','रक्तमोक्षण','शिरोधारा','कटिबस्ती','जानुबस्ती','ग्रीवाबस्ती','पिंडस्वेद','नेत्रतर्पण','संसर्जन क्रम'].forEach(v=>options.append(new Option(v,v)));form.append(options);
for(const [key,label] of [['medicine','औषध / तैल / द्रव्य'],['dose','मात्रा व एकक'],['duration','कालावधी (मिनिटे / इतर)'],['site','स्थान / शरीराचा भाग'],['before','प्रक्रियेपूर्व vitals'],['after','प्रक्रियेनंतर vitals'],['response','प्रतिसाद / सम्यक लक्षणे'],['adverse','प्रतिकूल घटना / केलेली कार्यवाही'],['staff','प्रक्रिया करणाऱ्याचे नाव'],['notes','डॉक्टरांच्या सूचना / इतर निरीक्षणे']])field(key,label);
const charge=field('charge','शुल्क नोंद (₹; ऐच्छिक)','number');charge.min=0;charge.step='0.01';
const confirm=document.createElement('label');confirm.innerHTML='<input type="checkbox" required style="width:auto"> ही काल्पनिक चाचणी नोंद आहे.';form.append(confirm);
const save=document.createElement('button');save.type='submit';save.textContent='नमुना session जोडा';save.disabled=true;form.append(save);const status=document.createElement('p');status.setAttribute('role','status');form.append(status);section.append(form);
const list=document.createElement('div');section.append(list);
const labels={course:'कोर्स',day:'दिवस',date:'तारीख',time:'वेळ',stage:'टप्पा',procedure:'प्रक्रिया',medicine:'औषध / तैल',dose:'मात्रा',duration:'कालावधी',site:'स्थान',before:'पूर्व vitals',after:'नंतरचे vitals',response:'प्रतिसाद',adverse:'प्रतिकूल घटना / कार्यवाही',staff:'प्रक्रिया करणारे',notes:'सूचना',charge:'शुल्क ₹'};
function printRecord(r){const box=document.getElementById('case-content');box.replaceChildren();const heading=document.createElement('h2');heading.textContent='Vishnu Ayurved Clinic · पंचकर्म नमुना नोंद';box.append(heading);for(const text of ['Dr. Jadhav V. R. · Udgir · 95183 55385','काल्पनिक मसुदा — उपचारासाठी वापरू नये',patients.get(r.patient)?.name||r.patient,...Object.entries(labels).filter(([key])=>r[key]!=='').map(([key,label])=>`${label}: ${r[key]}`)]){const p=document.createElement('p');p.textContent=text;box.append(p)}document.getElementById('case').showModal()}
function draw(){list.replaceChildren();const h=document.createElement('h3');h.textContent=`तात्पुरत्या session नोंदी: ${records.length}`;list.append(h);for(const r of records){const row=document.createElement('div');row.className='row';const text=document.createElement('span');text.textContent=`${patients.get(r.patient)?.name} · ${r.course} · दिवस ${r.day} · ${r.date} · ${r.procedure}`;const button=document.createElement('button');button.textContent='नोंद / प्रिंट';button.onclick=()=>printRecord(r);row.append(text,button);list.append(row)}}
form.addEventListener('submit',async e=>{e.preventDefault();const r=Object.fromEntries(new FormData(form));for(const key of Object.keys(r))r[key]=r[key].trim();if(!syntheticId(r.patient)||!patients.has(r.patient)||!r.course||!r.procedure){status.textContent='रुग्ण, कोर्स आणि प्रक्रिया भरा.';return}if(records.some(x=>x.patient===r.patient&&x.course===r.course&&x.date===r.date&&x.time===r.time&&x.procedure===r.procedure)){status.textContent='याच कोर्सची अशी नोंद आधीच आहे. वेळ/प्रक्रिया तपासा.';return}try{const id=`${r.patient}-${crypto.randomUUID()}`;const previous=records.filter(x=>x.patient===r.patient);await putDemo('panchakarma',r.patient,[...previous,{...r,sessionId:id}]);records.push({...r,sessionId:id});draw();status.textContent='काल्पनिक session या डिव्हाइसवर जतन झाले. Cloudमध्ये नाही.'}catch{status.textContent='जतन झाले नाही; ब्राउझर साठवण तपासा.'};});
draw();document.dispatchEvent(new Event('opd-request-samples'));

allDemo('panchakarma').then(rows=>{for(const row of rows)if(Array.isArray(row.value))records.push(...row.value);draw();save.disabled=false}).catch(()=>{status.textContent='या ब्राउझरमध्ये स्थानिक साठवण उपलब्ध नाही; नोंद जतन करता येणार नाही.'});
