import {allDemo,putDemo,syntheticId} from './demo-store.mjs?v=31';
import {todayIST} from './patient-model.mjs?v=31';
const records=[];const patients=new Map();
const section=document.getElementById('panchakarma');section.replaceChildren();
const title=document.createElement('h2');title.textContent='Panchakarma · Daily sessions';section.append(title);
const notice=document.createElement('p');notice.className='notice';notice.textContent='Record procedures prescribed by the doctor. Sessions are stored on this device and included in manual backups.';section.append(notice);
const form=document.createElement('form');const grid=document.createElement('div');grid.className='form-grid';form.append(grid);
function field(name,label,type='text'){const l=document.createElement('label');l.textContent=label;const input=document.createElement(type==='select'?'select':'input');input.name=name;if(type!=='select')input.type=type;input.maxLength=600;l.append(input);grid.append(l);return input}
const select=field('patient','Patient *','select');select.required=true;
function patientsChanged(){const previous=select.value;select.replaceChildren();const first=new Option('Select patient','');select.append(first);for(const p of patients.values())select.append(new Option(`${p.name} · ${p.id}`,p.id));if(patients.has(previous))select.value=previous}
document.addEventListener('opd-samples-ready',e=>{e.detail.forEach(p=>patients.set(p.id,p));patientsChanged()});document.addEventListener('opd-added',e=>{patients.set(e.detail.id,e.detail);patientsChanged()});
const course=field('course','Course name *');course.required=true;course.placeholder='e.g. Treatment course';
const day=field('day','Course day *','number');day.min=1;day.max=365;day.step=1;day.required=true;
const date=field('date','Procedure date *','date');date.required=true;date.value=todayIST();date.max=todayIST();
field('time','Time','time');
const stage=field('stage','Stage','select');['Purvakarma','Pradhanakarma','Paschatkarma','Local procedure','Other'].forEach(v=>stage.append(new Option(v,v)));
const procedure=field('procedure','Procedure *');procedure.required=true;procedure.setAttribute('list','pk-procedures');const options=document.createElement('datalist');options.id='pk-procedures';['Deepana-Pachana','Snehapana','Abhyanga','Swedana','Vamana','Virechana','Niruha Basti','Anuvasana Basti','Matra Basti','Nasya','Raktamokshana','Shirodhara','Kati Basti','Janu Basti','Greeva Basti','Pinda Sweda','Netra Tarpana','Samsarjana Krama'].forEach(v=>options.append(new Option(v,v)));form.append(options);
for(const [key,label] of [['medicine','Medicine / oil / material'],['dose','Dose and unit'],['duration','Duration (minutes / other)'],['site','Site / body area'],['before','Vitals before procedure'],['after','Vitals after procedure'],['response','Response / Samyak signs'],['adverse','Adverse event / action taken'],['staff','Staff member'],['notes','Doctor instructions / other observations']])field(key,label);
const charge=field('charge','Session charge (INR; optional)','number');charge.min=0;charge.step='0.01';

const save=document.createElement('button');save.type='submit';save.textContent='Add session';save.disabled=true;form.append(save);const status=document.createElement('p');status.setAttribute('role','status');form.append(status);section.append(form);
const list=document.createElement('div');section.append(list);
const labels={course:'Course',day:'Day',date:'Date',time:'Time',stage:'Stage',procedure:'Procedure',medicine:'Medicine / oil',dose:'Dose',duration:'Duration',site:'Site',before:'Pre-procedure vitals',after:'Post-procedure vitals',response:'Response',adverse:'Adverse event / action',staff:'Staff',notes:'Instructions',charge:'Charge INR'};
function printRecord(r){const box=document.getElementById('case-content');box.replaceChildren();const heading=document.createElement('h2');heading.textContent='Vishnu Ayurved Clinic Panchakarma record';box.append(heading);for(const text of ['Dr. Jadhav V. R. · Udgir · 95183 55385','Panchakarma session record',patients.get(r.patient)?.name||r.patient,...Object.entries(labels).filter(([key])=>r[key]!=='').map(([key,label])=>`${label}: ${r[key]}`)]){const p=document.createElement('p');p.textContent=text;box.append(p)}document.getElementById('case').showModal()}
function draw(){list.replaceChildren();const h=document.createElement('h3');h.textContent=`Local sessions: ${records.length}`;list.append(h);for(const r of records){const row=document.createElement('div');row.className='row';const text=document.createElement('span');text.textContent=`${patients.get(r.patient)?.name} · ${r.course} · Day ${r.day} · ${r.date} · ${r.procedure}`;const button=document.createElement('button');button.textContent='View / print';button.onclick=()=>printRecord(r);row.append(text,button);list.append(row)}}
form.addEventListener('submit',async e=>{e.preventDefault();const r=Object.fromEntries(new FormData(form));for(const key of Object.keys(r))r[key]=r[key].trim();if(!syntheticId(r.patient)||!patients.has(r.patient)||!r.course||!r.procedure){status.textContent='Select patient and enter course and procedure.';return}if(records.some(x=>x.patient===r.patient&&x.course===r.course&&x.date===r.date&&x.time===r.time&&x.procedure===r.procedure)){status.textContent='A matching course session already exists. Check time and procedure.';return}try{const id=`${r.patient}-${crypto.randomUUID()}`;const previous=records.filter(x=>x.patient===r.patient);await putDemo('panchakarma',r.patient,[...previous,{...r,sessionId:id}]);records.push({...r,sessionId:id});draw();status.textContent='Session saved on this device only.'}catch{status.textContent='Save failed. Check browser storage.'};});
draw();document.dispatchEvent(new Event('opd-request-samples'));

allDemo('panchakarma').then(rows=>{for(const row of rows)if(Array.isArray(row.value))records.push(...row.value);draw();save.disabled=false}).catch(()=>{status.textContent='Local storage unavailable. Cannot save the session.'});
