const section=document.getElementById('reports');
section.innerHTML=`<h2>मासिक व कस्टम अहवाल · नमुना</h2><p class="notice">येथे फक्त डेमो/या टॅबमधील नोंदी दिसतात. तारीख नसलेल्या नमुना रुग्णांची गणना होत नाही. हा अहवाल Cloud मधील माहिती दाखवत नाही.</p><div class="form-grid report-filters"><label>महिना<input id="month" type="month"></label><label>तारखेपासून<input id="report-from" type="date"></label><label>तारखेपर्यंत<input id="report-to" type="date"></label><label>प्रकार<select id="report-type"><option value="">सर्व</option><option>नवीन</option><option>फॉलो-अप</option></select></label><label>शोध: नाव / ID / गाव<input id="report-search" type="search"></label></div><div id="report-summary" class="stats"></div><button id="report-csv" type="button">CSV डाउनलोड</button> <button id="report-print" type="button">A4 अहवाल प्रिंट / PDF</button><div id="report-groups"></div><div id="report-table" class="report-table"></div>`;
const patients=new Map();
const get=id=>document.getElementById(id),month=get('month'),from=get('report-from'),to=get('report-to'),type=get('report-type'),search=get('report-search');
function localMonth(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${o.year}-${o.month}`}
month.value=localMonth();function syncMonth(){if(/^\d{4}-\d{2}$/.test(month.value)){from.value=month.value+'-01';const [y,m]=month.value.split('-').map(Number);to.value=`${y}-${String(m).padStart(2,'0')}-${String(new Date(y,m,0).getDate()).padStart(2,'0')}`}draw()}
function esc(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function draw(){const all=[...patients.values()];const q=search.value.trim().toLocaleLowerCase();const invalid=from.value&&to.value&&from.value>to.value;const rows=invalid?[]:all.filter(p=>{const date=p.visitDate||'';return date&&(!from.value||date>=from.value)&&(!to.value||date<=to.value)&&(!type.value||p.type===type.value)&&(!q||[p.name,p.id,p.village].join(' ').toLocaleLowerCase().includes(q))}).sort((a,b)=>(a.visitDate||'').localeCompare(b.visitDate||'')||a.name.localeCompare(b.name));
 const byVillage=new Map();for(const p of rows){const key=p.village||'गाव नोंद नाही';byVillage.set(key,(byVillage.get(key)||0)+1)}
 const summary=get('report-summary');summary.replaceChildren();for(const [label,value]of [['एकूण भेटी',rows.length],['नवीन',rows.filter(p=>p.type==='नवीन').length],['फॉलो-अप',rows.filter(p=>p.type==='फॉलो-अप').length],['स्वतंत्र रुग्ण',new Set(rows.map(p=>p.id)).size]]){const card=document.createElement('article');const s=document.createElement('span');s.textContent=label;const b=document.createElement('strong');b.textContent=String(value);card.append(s,b);summary.append(card)}
 const groups=get('report-groups');groups.replaceChildren();const h=document.createElement('h3');h.textContent='गावानुसार भेटी';groups.append(h);const gp=document.createElement('p');gp.textContent=[...byVillage].map(([v,n])=>`${v}: ${n}`).join(' · ')||'या कालावधीसाठी नोंदी नाहीत';groups.append(gp);
 const table=get('report-table');table.replaceChildren();if(invalid){table.textContent='“तारखेपासून” ही तारीख “तारखेपर्यंत” तारखेच्या आधी निवडा.';return}const t=document.createElement('table');t.innerHTML='<thead><tr><th>तारीख</th><th>रुग्ण</th><th>Patient ID</th><th>प्रकार</th><th>गाव</th></tr></thead>';const body=document.createElement('tbody');for(const p of rows){const tr=document.createElement('tr');for(const v of [p.visitDate,p.name,p.id,p.type,p.village]){const td=document.createElement('td');td.textContent=v||'—';tr.append(td)}body.append(tr)}t.append(body);table.append(t)}
document.addEventListener('opd-samples-ready',e=>{for(const p of e.detail)patients.set(p.id,p);draw()});document.addEventListener('opd-added',e=>{patients.set(e.detail.id,e.detail);draw()});
month.addEventListener('change',syncMonth);for(const el of [from,to,type,search])el.addEventListener(el===search?'input':'change',draw);
get('report-csv').addEventListener('click',()=>{const head=['तारीख','रुग्णाचे नाव','Patient ID','प्रकार','गाव','मोबाइल'];const rows=[...patients.values()].filter(p=>p.visitDate&&(!from.value||p.visitDate>=from.value)&&(!to.value||p.visitDate<=to.value)&&(!type.value||p.type===type.value)&&(!search.value||[p.name,p.id,p.village].join(' ').toLocaleLowerCase().includes(search.value.trim().toLocaleLowerCase())));const csv='\uFEFF'+[head,...rows.map(p=>[p.visitDate,p.name,p.id,p.type,p.village,p.mobile])].map(row=>row.map(esc).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`vishnu-ayurved-opd-${from.value||'from'}-${to.value||'to'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
get('report-print').addEventListener('click',()=>{document.body.classList.add('print-report');window.print()});window.addEventListener('afterprint',()=>document.body.classList.remove('print-report'));
document.dispatchEvent(new Event('opd-request-samples'));
