import {monthRange,reportRows,reportCsv} from './report-model.mjs';
const section=document.getElementById('reports');
section.innerHTML=`<div class="report-letterhead"><strong>विष्णु आयुर्वेद क्लिनिक आणि पंचकर्म सेंटर, उदगीर</strong><p>डॉ. विष्णुकांत आर. जाधव · BAMS, MD (Ayurved), Ph.D. Scholar</p></div><h2>मासिक व कस्टम अहवाल · नमुना</h2><p id="report-period" aria-live="polite"></p><p class="notice">या यादीत सध्या उपलब्ध नमुना intake नोंदी मोजल्या आहेत; हा संपूर्ण भेटींचा इतिहास नाही. Firebase syncमधून या यादीत आलेल्या नोंदीही समाविष्ट आहेत. तारीख नसलेल्या नोंदी मोजल्या जात नाहीत.</p><div class="form-grid report-filters"><label>महिना<input id="month" type="month"></label><label>तारखेपासून<input id="report-from" type="date"></label><label>तारखेपर्यंत<input id="report-to" type="date"></label><label>प्रकार<select id="report-type"><option value="">सर्व</option><option>नवीन</option><option>फॉलो-अप</option></select></label><label>शोध: नाव / ID / गाव / मोबाइल<input id="report-search" type="search"></label></div><div id="report-summary" class="stats"></div><button id="report-csv" type="button">CSV डाउनलोड</button> <button id="report-print" type="button">A4 अहवाल प्रिंट / PDF</button><div id="report-groups"></div><div id="report-table" class="report-table"></div>`;
const patients=new Map();
const get=id=>document.getElementById(id),month=get('month'),from=get('report-from'),to=get('report-to'),type=get('report-type'),search=get('report-search');
function localMonth(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit'}).formatToParts(new Date());const o=Object.fromEntries(parts.map(p=>[p.type,p.value]));return `${o.year}-${o.month}`}
month.value=localMonth();
function syncMonth(){const range=monthRange(month.value);from.value=range.from;to.value=range.to;draw()}
function filteredRows(){return reportRows([...patients.values()],{from:from.value,to:to.value,type:type.value,query:search.value})}
function draw(){const invalid=Boolean(from.value&&to.value&&from.value>to.value);const rows=filteredRows();
 get('report-csv').disabled=invalid||rows.length===0;get('report-print').disabled=invalid||rows.length===0;
 get('report-period').textContent=`कालावधी: ${from.value||'सुरुवातीपासून'} ते ${to.value||'शेवटपर्यंत'} · प्रकार: ${type.value||'सर्व'}${search.value.trim()?' · शोध: '+search.value.trim():''}`;
 const byVillage=new Map();for(const p of rows){const key=p.village||'गाव नोंद नाही';byVillage.set(key,(byVillage.get(key)||0)+1)}
 const summary=get('report-summary');summary.replaceChildren();for(const [label,value]of [['एकूण intake नोंदी',rows.length],['नवीन',rows.filter(p=>p.type==='नवीन').length],['फॉलो-अप',rows.filter(p=>p.type==='फॉलो-अप').length],['स्वतंत्र Patient IDs',new Set(rows.map(p=>p.id)).size]]){const card=document.createElement('article');const s=document.createElement('span');s.textContent=label;const b=document.createElement('strong');b.textContent=String(value);card.append(s,b);summary.append(card)}
 const groups=get('report-groups');groups.replaceChildren();const h=document.createElement('h3');h.textContent='गावानुसार नोंदी';groups.append(h);const gp=document.createElement('p');gp.textContent=[...byVillage].map(([v,n])=>`${v}: ${n}`).join(' · ')||'या कालावधीसाठी नोंदी नाहीत';groups.append(gp);
 const table=get('report-table');table.replaceChildren();if(invalid){table.textContent='“तारखेपासून” ही तारीख “तारखेपर्यंत” तारखेच्या आधी निवडा.';return}const t=document.createElement('table');t.innerHTML='<thead><tr><th>तारीख</th><th>रुग्ण</th><th>Patient ID</th><th>प्रकार</th><th>गाव</th></tr></thead>';const body=document.createElement('tbody');for(const p of rows){const tr=document.createElement('tr');for(const v of [p.visitDate,p.name,p.id,p.type,p.village]){const td=document.createElement('td');td.textContent=v||'—';tr.append(td)}body.append(tr)}t.append(body);table.append(t);if(!rows.length){const empty=document.createElement('p');empty.textContent='निवडलेल्या फिल्टरनुसार नोंदी नाहीत.';table.append(empty)}}
document.addEventListener('opd-samples-ready',e=>{for(const p of e.detail)patients.set(p.id,p);draw()});document.addEventListener('opd-added',e=>{patients.set(e.detail.id,e.detail);draw()});
month.addEventListener('change',syncMonth);for(const el of [from,to,type,search])el.addEventListener(el===search?'input':'change',()=>{if(el===from||el===to)month.value='';draw()});
get('report-csv').addEventListener('click',()=>{const rows=filteredRows();if(!rows.length)return;const csv=reportCsv(rows);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`vishnu-ayurved-opd-${from.value||'from'}-${to.value||'to'}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
get('report-print').addEventListener('click',()=>{if(!filteredRows().length)return;document.body.classList.add('print-report');window.print()});window.addEventListener('afterprint',()=>document.body.classList.remove('print-report'));
syncMonth();
document.dispatchEvent(new Event('opd-request-samples'));
