const section=document.getElementById('review');
section.innerHTML=`<h2>डॉक्टर पुनरावलोकन · नमुना</h2><p class="notice">फक्त डेमो workflow. या यादीतली केस आणि नोंदी Cloud मध्ये साठत नाहीत; Refresh केल्यावर मिटतात. प्रत्यक्ष विद्यार्थी/डॉक्टर access Firebase नियमांशी जोडलेला नाही.</p><label>स्थिती<select id="review-filter"><option value="pending">पुनरावलोकन बाकी</option><option value="all">सर्व</option><option value="reviewed">पुनरावलोकन पूर्ण</option></select></label><p id="review-count" role="status"></p><div id="review-list"></div>`;
const items=new Map(),filter=document.getElementById('review-filter'),list=document.getElementById('review-list');
document.addEventListener('opd-clinical-review-submit',e=>{const {patient,data,submittedAt}=e.detail,old=items.get(patient.id);items.set(patient.id,{patient,data,submittedAt,status:'pending',note:old?.note||''});draw()});
function draw(){list.replaceChildren();const selected=[...items.values()].filter(r=>filter.value==='all'||(filter.value==='reviewed'?r.status==='reviewed':r.status==='pending')).sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt));document.getElementById('review-count').textContent=`${selected.length} नमुना केस · ${[...items.values()].filter(r=>r.status==='pending').length} बाकी`;
 if(!selected.length){list.textContent='या filter मध्ये केस नाही. केस-टेकिंगमध्ये नोंद जतन करून “डॉक्टरांकडे पुनरावलोकनासाठी पाठवा” दाबा.';return}
 for(const r of selected){const card=document.createElement('article');card.className='panel review-card';const h=document.createElement('h3');h.textContent=r.patient.name;const detail=document.createElement('p');detail.textContent=`${r.patient.id} · भेट ${r.patient.visitDate||'तारीख नाही'} · पाठवले ${new Intl.DateTimeFormat('mr-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(r.submittedAt))} · ${r.status==='pending'?'पुनरावलोकन बाकी':'पुनरावलोकन पूर्ण'}`;
  const complaints=(r.data.complaints||[]).filter(c=>c.text).map(c=>c.text);const p=document.createElement('p');p.textContent='मुख्य तक्रारी: '+(complaints.join(' · ')||'नोंद नाही');const open=document.createElement('button');open.type='button';open.textContent='केस पेपर व नोंद उघडा';open.onclick=()=>document.dispatchEvent(new CustomEvent('opd-open-patient',{detail:r.patient}));card.append(h,detail,p,open);
  const label=document.createElement('label');label.textContent='डॉक्टरांची पुनरावलोकन नोंद';const note=document.createElement('textarea');note.maxLength=1500;note.value=r.note;label.append(note);const mark=document.createElement('button');mark.type='button';mark.textContent=r.status==='reviewed'?'पुनरावलोकन पुन्हा बाकी करा':'पुनरावलोकन पूर्ण म्हणून नोंदवा';mark.onclick=()=>{r.note=note.value.trim();r.status=r.status==='reviewed'?'pending':'reviewed';draw()};card.append(label,mark);list.append(card)}
}
filter.addEventListener('change',draw);draw();
