import {allDemo,putDemo} from './demo-store.mjs?v=29';
const section=document.getElementById('review');
section.innerHTML=`<h2>Doctor review · Sample</h2><p>Demo review queue only. Review entries and notes are saved on this device and included in local backups. They do not sync between devices. Marking a review is a demo workflow, not clinical approval.</p><label>Status<select id="review-filter"><option value="pending">Pending review</option><option value="all">All</option><option value="reviewed">Review complete</option></select></label><p id="review-count" role="status"></p><div id="review-list"></div>`;
const items=new Map(),filter=document.getElementById('review-filter'),list=document.getElementById('review-list');
const ready=allDemo('review').then(rows=>{for(const row of rows){const r=row.value;if(r?.patient?.id===row.id&&['pending','reviewed'].includes(r.status)&&typeof r.submittedAt==='string')items.set(row.id,r)}draw()}).catch(()=>{document.getElementById('review-count').textContent='Could not load local review records.'});
document.addEventListener('opd-clinical-review-submit',async e=>{await ready;const {patient,data,submittedAt}=e.detail,old=items.get(patient.id);const next={patient,data,submittedAt,status:'pending',note:old?.note||''};try{await putDemo('review',patient.id,next);items.set(patient.id,next);draw()}catch{document.getElementById('review-count').textContent='Review entry was not saved. Check browser storage.'}});
function draw(){list.replaceChildren();const selected=[...items.values()].filter(r=>filter.value==='all'||(filter.value==='reviewed'?r.status==='reviewed':r.status==='pending')).sort((a,b)=>b.submittedAt.localeCompare(a.submittedAt));document.getElementById('review-count').textContent=`${selected.length} sample cases · ${[...items.values()].filter(r=>r.status==='pending').length} pending`;
 if(!selected.length){list.textContent='No cases in this filter. Save a sample examination and choose Send to doctor review.';return}
 for(const r of selected){const card=document.createElement('article');card.className='panel review-card';const h=document.createElement('h3');h.textContent=r.patient.name;const detail=document.createElement('p');detail.textContent=`${r.patient.id} · visit ${r.patient.visitDate||'No date'} · submitted ${new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(r.submittedAt))} · ${r.status==='pending'?'Pending review':'Review complete'}`;
  const complaints=(r.data.complaints||[]).filter(c=>c.text).map(c=>c.text);const p=document.createElement('p');p.textContent='Chief complaints: '+(complaints.join(' · ')||'Not recorded');const open=document.createElement('button');open.type='button';open.textContent='Open case paper and examination';open.onclick=()=>document.dispatchEvent(new CustomEvent('opd-open-patient',{detail:r.patient}));card.append(h,detail,p,open);
  const label=document.createElement('label');label.textContent='Doctor review note';const note=document.createElement('textarea');note.maxLength=1500;note.value=r.note;label.append(note);const mark=document.createElement('button');mark.type='button';mark.textContent=r.status==='reviewed'?'Reopen review':'Mark review complete';mark.onclick=async()=>{mark.disabled=true;const next={...r,note:note.value.trim(),status:r.status==='reviewed'?'pending':'reviewed'};try{await putDemo('review',r.patient.id,next);items.set(r.patient.id,next);draw()}catch{mark.disabled=false;document.getElementById('review-count').textContent='Review update was not saved.'}};card.append(label,mark);list.append(card)}
}
filter.addEventListener('change',draw);draw();
