import {createAuth,firebaseErrorMessage} from './auth.mjs?v=34';
import {setAuthProvider} from './auth-context.mjs?v=34';
import {useStudentStore,putDemo,allDemo,syncRows,acceptCloud} from './demo-store.mjs?v=34';
import {syncClinic} from './clinic-sync.mjs?v=34';
import {todayIST,validatePatient,searchPatients} from './patient-model.mjs?v=34';
const get=id=>document.getElementById(id);let auth,busy=false,epoch=0,timer;const form=get('student-registration');form.elements.visitDate.value=todayIST();form.elements.visitDate.max=todayIST();
let device;const storedUid=localStorage.getItem('vac-student-device-uid');
get('student-login').querySelector('button').disabled=true;
async function ready(uid){useStudentStore(uid);await import('./clinical.mjs?v=34');get('student-device').textContent=uid;get('student-login').querySelector('button').disabled=false;await draw();}

get('student-login').onsubmit=async e=>{e.preventDefault();get('student-login-panel').hidden=true;get('student-work').hidden=false;get('student-entry-name').value=get('student-name').value.trim();};
try{const r=await fetch('./firebase-config.json',{cache:'no-store'});auth=createAuth(await r.json());device=await auth.openDevice(localStorage.getItem('vac-student-device-token'));localStorage.setItem('vac-student-device-token',device.refreshToken);localStorage.setItem('vac-student-device-uid',device.uid);setAuthProvider(auth);await ready(device.uid);get('student-login-status').textContent=device.role==='student'?'Device approved.':'Ask the Owner to approve this device ID in Settings. Entries can be saved locally while waiting.';await draw();}catch(error){get('student-login-status').textContent=firebaseErrorMessage(error)+' Enable Anonymous sign-in in Firebase Authentication.';if(/^[A-Za-z0-9_-]{1,128}$/.test(storedUid||'')){device={uid:storedUid,role:'pending'};await ready(storedUid);get('student-login-status').textContent='Offline entry available on this previously registered device. Reopen online to reconnect.';}}
async function draw(){const rows=(await allDemo('intake')).map(r=>r.value),list=get('student-patients');list.replaceChildren();for(const p of searchPatients(rows,get('student-search').value)){const card=document.createElement('article');card.className='panel';const name=document.createElement('p');name.textContent=p.name+' · '+p.id+' · Entry by: '+(p.enteredByName||'Not recorded');const open=document.createElement('button');open.textContent='Record examination';open.onclick=()=>{const box=get('case-content');box.replaceChildren();const heading=document.createElement('h2');heading.textContent=p.name;box.append(heading);document.dispatchEvent(new CustomEvent('opd-case-open',{detail:p}));get('case').showModal();const forward=box.querySelector('.clinical-editor button:last-child');if(forward?.textContent==='Send to doctor review')forward.remove();};card.append(name,open);list.append(card);}}
form.onsubmit=async e=>{e.preventDefault();const user=auth?.current()||device;if(!['student','pending'].includes(user?.role)){get('student-save-status').textContent='Sign-in expired. Sign in again.';return;}const p=Object.fromEntries(new FormData(form));for(const k of ['name','village','mobile'])p[k]=p[k].trim();const error=validatePatient(p);if(error){get('student-save-status').textContent=error;return;}const button=form.querySelector('button');button.disabled=true;try{p.id='VAC-OPD-'+p.visitDate.replaceAll('-','')+'-'+crypto.randomUUID();p.type='नवीन';p.enteredByName=get('student-entry-name').value.trim();if(!p.enteredByName)throw new Error('STUDENT_NAME_REQUIRED');p.createdBy=user.uid;p.createdAt=p.enteredAt=new Date().toISOString();await putDemo('intake',p.id,p);get('student-save-status').textContent='Saved on this device: '+p.id;form.reset();form.elements.visitDate.value=todayIST();form.elements.visitDate.max=todayIST();await draw();await sync();}catch{get('student-save-status').textContent='Save failed. Your entries remain in the form.';}finally{button.disabled=false;}};
async function sync(){if(busy)return;let user=auth?.current();const attempt=epoch;if(!user)return;try{user=await auth.checkDevice()}catch(error){get('student-cloud-status').textContent=firebaseErrorMessage(error);return}if(user.role!=='student'){get('student-cloud-status').textContent='Local only: Owner approval is pending or revoked.';return;}busy=true;get('student-sync').disabled=true;try{const result=await syncClinic({auth,localRows:syncRows,ack:acceptCloud,isCurrent:()=>attempt===epoch&&auth.current()?.uid===user.uid});get('student-cloud-status').textContent=`${result.uploaded} uploaded · ${result.conflicts.length} conflicts · ${result.failures.length} failed. `+(result.failures.length?result.failures.map(x=>x.code).join(', '):'');await draw();}catch(error){get('student-cloud-status').textContent=firebaseErrorMessage(error)+' Local entries are retained.';}finally{busy=false;get('student-sync').disabled=false;}}
get('student-sync').onclick=sync;get('student-search').oninput=draw;get('student-close').onclick=()=>get('case').close();get('student-out').onclick=()=>{epoch++;get('student-work').hidden=true;get('student-login-panel').hidden=false;get('student-name').value='';get('student-entry-name').value=''};window.addEventListener('online',sync);window.addEventListener('opd-local-save',()=>{clearTimeout(timer);timer=setTimeout(sync,1500)});

if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
