import {createAuth,firebaseErrorMessage} from './auth.mjs?v=32';
import {setAuthProvider} from './auth-context.mjs?v=32';
import {useStudentStore,putDemo,allDemo,syncRows,acceptCloud} from './demo-store.mjs?v=32';
import {syncClinic} from './clinic-sync.mjs?v=32';
import {todayIST,validatePatient,searchPatients} from './patient-model.mjs?v=32';
const get=id=>document.getElementById(id);let auth,busy=false,epoch=0,timer;const form=get('student-registration');form.elements.visitDate.value=todayIST();form.elements.visitDate.max=todayIST();
try{const r=await fetch('./firebase-config.json',{cache:'no-store'});auth=createAuth(await r.json());}catch{get('student-login-status').textContent='Firebase unavailable.';get('student-login').querySelector('button').disabled=true;}
get('student-login').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const user=await auth.login(get('student-email').value,get('student-password').value);if(user.role!=='student'){auth.logout();throw new Error('Use Doctor / Owner sign-in for this account.');}useStudentStore(user.uid);setAuthProvider(auth);await import('./clinical.mjs?v=32');get('student-login-panel').hidden=true;get('student-work').hidden=false;await draw();await sync();}catch(error){get('student-login-status').textContent=firebaseErrorMessage(error);button.disabled=false;}finally{get('student-password').value='';}};
async function draw(){const rows=(await allDemo('intake')).map(r=>r.value),list=get('student-patients');list.replaceChildren();for(const p of searchPatients(rows,get('student-search').value)){const card=document.createElement('article');card.className='panel';const name=document.createElement('p');name.textContent=p.name+' · '+p.id;const open=document.createElement('button');open.textContent='Record examination';open.onclick=()=>{const box=get('case-content');box.replaceChildren();const heading=document.createElement('h2');heading.textContent=p.name;box.append(heading);document.dispatchEvent(new CustomEvent('opd-case-open',{detail:p}));get('case').showModal();const forward=box.querySelector('.clinical-editor button:last-child');if(forward?.textContent==='Send to doctor review')forward.remove();};card.append(name,open);list.append(card);}}
form.onsubmit=async e=>{e.preventDefault();const user=auth?.current();if(user?.role!=='student'){get('student-save-status').textContent='Sign-in expired. Sign in again.';return;}const p=Object.fromEntries(new FormData(form));for(const k of ['name','village','mobile'])p[k]=p[k].trim();const error=validatePatient(p);if(error){get('student-save-status').textContent=error;return;}const button=form.querySelector('button');button.disabled=true;try{p.id='VAC-OPD-'+p.visitDate.replaceAll('-','')+'-'+crypto.randomUUID();p.type='नवीन';p.createdBy=user.uid;p.createdAt=p.enteredAt=new Date().toISOString();await putDemo('intake',p.id,p);get('student-save-status').textContent='Saved on this student account: '+p.id;form.reset();form.elements.visitDate.value=todayIST();await draw();await sync();}catch{get('student-save-status').textContent='Save failed. Your entries remain in the form.';}finally{button.disabled=false;}};
async function sync(){if(busy)return;const user=auth?.current(),attempt=epoch;if(user?.role!=='student')return;busy=true;get('student-sync').disabled=true;try{const result=await syncClinic({auth,localRows:syncRows,ack:acceptCloud,isCurrent:()=>attempt===epoch&&auth.current()?.uid===user.uid});get('student-cloud-status').textContent=`${result.uploaded} uploaded · ${result.conflicts.length} conflicts · ${result.failures.length} failed. `+(result.failures.length?result.failures.map(x=>x.code).join(', '):'');await draw();}catch(error){get('student-cloud-status').textContent=firebaseErrorMessage(error)+' Local entries are retained.';}finally{busy=false;get('student-sync').disabled=false;}}
get('student-sync').onclick=sync;get('student-search').oninput=draw;get('student-close').onclick=()=>get('case').close();get('student-out').onclick=()=>{epoch++;auth.logout();location.reload()};window.addEventListener('online',sync);window.addEventListener('opd-local-save',()=>{clearTimeout(timer);timer=setTimeout(sync,1500)});
